stages:
  - build

make_rpm:
  image: ppc64le/centos
  stage: build
  only:
    #- tags
    - build-1.5
  tags:
    - ppc64le
    - docker
    - priviledged
  before_script:
    - yum install -y epel-release
    - yum install -y bzip2 git GitPython mock PyYAML svn wget
    - python setup_environment.py joe
    - chown -R joe /builds
    - BUILD_DIR=$PWD
  script:
    #- su - joe -c "python host-os-build.py --package libvirt"
    - runuser -u joe "python --version"
    - runuser -u joe "ls -l $BUILD_DIR/host-os-build.py"
    - runuser -u joe "python $BUILD_DIR/host-os-build.py --package libvirt"
