stages:
  - build

make_rpm:
  image: ppc64le/centos
  stage: build
  only:
    #- tags
    - build-1.5
  tags:
    - ppc64le
    - docker
    - priviledged
  before_script:
    - yum install -y epel-release
    - yum install -y bzip2 git GitPython mock PyYAML svn wget
    - python setup_environment.py bob
    - chown -R bob /builds
    - BUILD_DIR=$PWD
    - which python
  script:
    #- su - bob -c "python host-os-build.py --package libvirt"
    - runuser -u bob "python --version"
    - runuser -u bob "ls -l $BUILD_DIR/host-os-build.py"
    - runuser -u bob "python $BUILD_DIR/host-os-build.py --package libvirt"
