stages:
  - build

make_rpm:
  image: ppc64le/centos
  stage: build
  only:
    #- tags
    - build-1.5
  tags:
    - ppc64le
    - docker
    - priviledged
  before_script:
    - yum install -y epel-release
    - yum install -y bzip2 git GitPython mock PyYAML svn wget
    - python setup_environment.py joe
    - useradd joe
    - usermod -a -G mock joe
  script:
    #- su - joe -c "python host-os-build.py --package libvirt"
    - runsuser -l -u joe python host-os-build.py --package libvirt
