stages:
  - build

make_rpm:
  image: ppc64le/centos
  stage: build
  only:
    #- tags
    - build-1.5
  tags:
    - ppc64le
    - docker
    - priviledged
  before_script:
    - yum install -y epel-release
    - yum install -y bzip2 git GitPython mock PyYAML svn wget
    - useradd joe
    - usermod -a -G mock joe
    - python setup_environment.py joe
  script:
    - su joe -c "./host_os.py --verbose"
