stages:
  - build

make_rpm:
  image: ppc64le/centos
  stage: build
  only:
    #- tags
    - build
    - build-1.5
  tags:
    - ppc64le
    - docker
  before_script:
    - yum install -y epel-release
    - yum install -y $(cat requirements-dev.txt)
    - useradd joe
    - usermod -a -G mock joe
  script:
    - su joe -c "./host_os.py --verbose build-packages"
